
INSERT INTO GRUPOPARLAMENTARIO (ID, NOMBRE, VOTO) VALUES ('1', 'SOCIALISTA', 'FAVOR'),('2', 'POPULAR EN EL CONGRESO', 'CONTRA'),('3', 'VOXI', 'CONTRA'),('4', 'CONFEDERAL DE UNIDAS PODEMOS-EN COM� PODEM-GALICIA EN COM�N', 'FAVOR'),('5', 'REPUBLICANO', 'FAVOR')
INSERT INTO GRUPOPARLAMENTARIO (ID, NOMBRE, VOTO) VALUES ('6', 'PLURAL', 'FAVOR'),('7', 'CIUDADANSOI', 'CONTRA'),('8', 'VASCO (EAJ-PNV)', 'FAVOR'),('9', 'EUSKAL HERRIA BILDU', 'FAVOR'),('10', 'MIXTO', 'CONTRA')
INSERT INTO PARTIDO(ID, DESCRIPCION, NOMBRE, VOTO, GRUPOPARLAMENTARIO_ID) VALUES ('1', 'DE IZQUIERDAS', 'PSOE', 'FAVOR', 1),('2', 'DE IZQUIERDAS CATALANES', 'PSC', 'FAVOR', 1),('3', 'DE DERECHAS', 'PP', 'CONTRA', 2),('4', 'DE DERECHAS', 'VOX', 'CONTRA', 3)
INSERT INTO PARTIDO(ID, DESCRIPCION, NOMBRE, VOTO, GRUPOPARLAMENTARIO_ID) VALUES ('5', 'DE IZQUIERDAS', 'UNIDAS PODEMOS', 'FAVOR', 4),('6', 'DE IZQUIERDAS CATALANES', 'EN COM� PODEM', 'FAVOR', 4),('7', 'DE IZQUIERDAS GALLEGOS', 'GALICIA EN COM�N', 'FAVOR', 4),('8', 'CATALANES SUBNORMALES', 'ERC', 'FAVOR', 5)
INSERT INTO PARTIDO(ID, DESCRIPCION, NOMBRE, VOTO, GRUPOPARLAMENTARIO_ID) VALUES ('9', 'DE IZQUIERDAS', 'SOBIRANISTES', 'FAVOR', 5),('10', 'CATALANES', 'JXCAT', 'FAVOR', 6),('11', 'DE IZQUIERDAS CON ERREJ�N', 'M�S PA�S-EQUO', 'FAVOR', 6),('12', 'DE IZQUIERDAS', 'M�S COMPROM�S', 'FAVOR', 6)
INSERT INTO PARTIDO(ID, DESCRIPCION, NOMBRE, VOTO, GRUPOPARLAMENTARIO_ID) VALUES ('13', 'NACIONALISTAS GALLEGOS DE IZQUIERDAS', 'BNG', 'FAVOR', 6),('14', 'CENTRO', 'CIUDADANOS', 'CONTRA', 7),('15', 'NACIONALISTAS VASCOS', 'EAJ-PNV', 'CONTRA', 8),('16', 'VASCOS', 'EH-BILDU', 'CONTRA', 9)
INSERT INTO PARTIDO(ID, DESCRIPCION, NOMBRE, VOTO, GRUPOPARLAMENTARIO_ID) VALUES ('17', 'CATALANES INDEPENDENTISTAS', 'CUP-PR', 'CONTRA', 10),('18', 'COALICI�N NAVARRA', 'UPN', 'CONTRA', 10),('19', 'COALICI�N CANARIA', 'CC-PNC', 'CONTRA', 10),('20', 'DE IZQUIERDAS CANARIO', 'NC', 'FAVOR', 10)
INSERT INTO PARTIDO(ID, DESCRIPCION, NOMBRE, VOTO, GRUPOPARLAMENTARIO_ID) VALUES ('21', 'PARTIDO C�NTABRO', 'PRC', 'FAVOR', 10),('22', 'PARTIDO DE TERUEL', 'TE', 'FAVOR', 10),('23', 'PARTIDO ASTURIANO', 'FORO', 'FAVOR', 10),
INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES ('1', '�BALOS', 'MECO', 'JOS� LUIS', 'FAVOR', 1),
('2', 'ABASCAL', 'CONDE', 'SANTIAGO', 'FAVOR', 2),
('3', 'ACEVES', 'GALINDO', 'JOS� LUIS', 'FAVOR', 1),
('4', 'AGIRRETXEA', 'URRESTI', 'JOSEBA ANDONI', 'FAVOR', 1),
('5', 'AIZCORBE', 'TORRA', 'JUAN JOS�', 'FAVOR', 1),
('6', 'AIZPURUA', 'ARZALLUS', 'MERTXE', 'FAVOR', 1),
('7', 'ALCARAZ', 'MARTOS', 'FRANCISCO JOS�', 'FAVOR', 1),
('8', 'ALFONSO', 'CEND�N', 'JAVIER', 'FAVOR', 1),
('9', 'ALMOD�BAR', 'BARCEL�', 'AGUST�N', 'FAVOR', 1),
('10', 'ALONSO', 'P�REZ', 'JOS� �NGEL', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('11', 'ALONSO', 'SU�REZ', 'MAR�A OLGA', 'FAVOR', 1),
('12', 'ALONSO-CUEVILLAS', 'i SAYROL', 'JAUME', 'FAVOR', 2),
('13', '�LVAREZ DE TOLEDO', 'PERALTA-RAMOS', 'CAYETANA', 'FAVOR', 1),
('14', '�LVAREZ', 'FANJUL', 'BEATRIZ', 'FAVOR', 1),
('15', 'ANDR�S', 'A��N', 'CARMEN', 'FAVOR', 1),
('16', 'ANDR�S', 'BAREA', 'JOSEFA', 'FAVOR', 1),
('17', 'ANGUITA', 'P�REZ', 'OMAR', 'FAVOR', 1),
('18', '�NGULO', 'ROMERO', 'MAR�A TERESA', 'FAVOR', 1),
('19', 'ANT�N', 'CACHO', 'JAVIER', 'FAVOR', 1),
('20', 'ARAGON�S', 'MENDIGUCH�A', 'CARLOS', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('21', 'ARANDA', 'VARGAS', 'FRANCISCO', 'FAVOR', 1),
('22', 'ARAUJO', 'MORALES', 'GEMMA', 'FAVOR', 2),
('23', 'ARRIBAS', 'MAROTO', 'MANUEL', 'FAVOR', 1),
('24', 'ARRIMADAS', 'GARC�A', 'IN�S', 'FAVOR', 1),
('25', 'ASARTA', 'CUEVAS', 'ALBERTO', 'FAVOR', 1),
('26', 'ASENS', 'LLODR�', 'JAUME', 'FAVOR', 1),
('27', 'ASOR�N', 'SALAR', 'L�ZARO', 'FAVOR', 1),
('28', 'BAL', 'FRANC�S', 'EDMUNDO', 'FAVOR', 1),
('29', 'BALDOV�', 'RODA', 'JOAN', 'FAVOR', 1),
('30', 'BA�OS', 'RUIZ', 'CARMEN', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('31', 'BARANDIARAN', 'BENITO', 'I�IGO', 'FAVOR', 1),
('32', 'BAS', 'CORUGEIRA', 'JAVIER', 'FAVOR', 2),
('33', 'BASSA', 'COLL', 'MONTSERRAT', 'FAVOR', 1),
('34', 'BEL', 'ACCENSI', 'FERRAN', 'FAVOR', 1),
('35', 'BELARRA', 'URTEAGA', 'IONE', 'FAVOR', 1),
('36', 'BELTR�N', 'VILLALBA', 'ANA MAR�A', 'FAVOR', 1),
('37', 'BERJA', 'VEGA', 'LAURA', 'FAVOR', 1),
('38', 'BERM�DEZ DE CASTRO', 'FERN�NDEZ', 'JOS� ANTONIO', 'FAVOR', 1),
('39', 'BETORET', 'COLL', 'VICENTE', 'FAVOR', 1),
('40', 'BLANQUEAR', '�LCARAZ', 'PATRICIA', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('41', 'BOADELLA', 'ESTEVE', 'GEN�S', 'FAVOR', 1),
('42', 'BORR�S', 'CASTANYER', 'LAURA', 'FAVOR', 2),
('43', 'BORR�S', 'PAB�N', 'MIREIA', 'FAVOR', 1),
('44', 'BORREGO', 'CORT�S', 'ISABEL MAR�A', 'FAVOR', 1),
('45', 'BOTELLA', 'G�MEZ', 'ANA MAR�A', 'FAVOR', 1),
('46', 'BOTRAN', 'PAHISSA', 'ALBERT', 'FAVOR', 1),
('47', 'BRAVO', 'BARCO', 'EVA', 'FAVOR', 1),
('48', 'BUENO', 'CAMPANARIO', 'EVA PATRICIA', 'FAVOR', 1),
('49', 'CABALLERO', 'GUTI�RREZ', 'HELENA', 'FAVOR', 1),
('50', 'CABEZ�N', 'CASAS', 'TOM�S', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('51', 'CALLEJAS', 'CANO', 'JUAN ANTONIO', 'FAVOR', 1),
('52', 'CALVO', 'LISTE', 'PABLO JUAN', 'FAVOR', 2),
('53', 'CALVO', 'POYATO', 'CARMEN', 'FAVOR', 1),
('54', 'CAMBRONERO', 'PIQUERAS', 'PABLO', 'FAVOR', 1),
('55', 'CA�ADELL', 'SALVIA', 'CONCEP', 'FAVOR', 1),
('56', 'CANALES', 'DUQUE', 'MARIANA DE GRACIA', 'FAVOR', 1),
('57', 'CANCELA', 'RODR�GUEZ', 'PILAR', 'FAVOR', 1),
('58', 'CA�IZARES', 'PACHECO', 'IN�S MAR�A', 'FAVOR', 1),
('59', 'CANTERA', 'DE CASTRO', 'ZAIDA', 'FAVOR', 1),
('60', 'CAPDEVILA', 'i ESTEVE', 'JOAN', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('61', 'CARAZO', 'HERMOSO', 'EDUARDO', 'FAVOR', 1),
('62', 'CARCEDO', 'ROCES', 'MAR�A LUISA', 'FAVOR', 2),
('63', 'CARRILLO', 'DE LOS REYES', 'BEATRIZ MICAELA', 'FAVOR', 1),
('64', 'CARVALHO', 'DANTAS', 'MAR�A', 'FAVOR', 1),
('65', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('66', 'CASARES', 'HONTA��N', 'PEDRO', 'FAVOR', 1),
('67', 'CASERO', '�VILA', 'ALBERTO', 'FAVOR', 1),
('68', 'CASTELL�N', 'RUBIO', 'MIGUEL �NGEL', 'FAVOR', 1),
('69', 'CASTILLO ', 'L�PEZ', 'ELENA', 'FAVOR', 1),
('70', 'CERD�N', 'LE�N', 'SANTOS', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES
('71', 'CERQUEIRO', 'GONZ�LEZ', 'JAVIER', 'FAVOR', 1),
('72', 'CHAMORRO', 'DELMO', 'RICARDO', 'FAVOR', 2),
('73', 'CLAVELL', 'L�PEZ', '�SCAR', 'FAVOR', 1),
('74', 'CONTRERAS', 'PEL�EZ', 'FRANCISCO JOS�', 'FAVOR', 1),
('75', 'CORT�S', 'CARBALLO', 'MARIO', 'FAVOR', 1),
('76', 'CORT�S', 'G�MEZ', 'ISMAEL', 'FAVOR', 1),
('77', 'CRESP�N', 'RUBIO', 'RAFAELA', 'FAVOR', 1),
('78', 'CRUZ-GUZM�N', 'GARC�A', 'MAR�A SOLEDAD', 'FAVOR', 1),
('79', 'CUATRECASAS', 'ASUA', 'JUAN', 'FAVOR', 1),
('80', 'DE LAS HERAS', 'FERN�NDEZ', 'PATRICIA', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES
('81', 'DE LUNA', 'TOBARRA', 'LLANOS', 'FAVOR', 1),
('82', 'DE MEER', 'M�NDEZ', 'ROC�O', 'FAVOR', 2),
('83', 'DE QUINTO', 'ROMERO', 'MARCOS', 'FAVOR', 1),
('84', 'DEL VALLE', 'DE ISCAR', 'JULIO', 'FAVOR', 1),
('85', 'DEL VALLE', 'RODR�GUEZ', 'EMILIO JES�S', 'FAVOR', 1),
('86', 'DELGADO', 'ARCE', 'CELSO LUIS', 'FAVOR', 1),
('87', 'D�AZ', 'G�MEZ', 'GUILLERMO', 'FAVOR', 1),
('88', 'D�AZ', 'P�REZ', 'YOLANDA', 'FAVOR', 1),
('89', 'DIOUF', 'DIOH', 'LUC ANDRE', 'FAVOR', 1),
('90', 'DUR�N', 'PERALTA', 'JOS� CARLOS', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('91', 'ECH�NIZ', 'SALGADO', 'JOS� IGNACIO', 'FAVOR', 1),
('92', 'ECHENIQUE', 'ROBBA', 'PABLO', 'FAVOR', 2),
('93', 'ELIZO', 'SERRANO', 'OD�N', 'FAVOR', 1),
('94', 'EITJA', 'CIUR�', 'FRANCESC XAVIER', 'FAVOR', 1),
('95', 'ERREJ�N GALV�N', 'I�IGO', 'PABLO', 'FAVOR', 1),
('96', 'ESPA�A', 'REINA', 'CAROLINA', 'FAVOR', 1),
('97', 'ESPEJO-SAAVEDRA', 'CONESA', 'JOS� MAR�A', 'FAVOR', 1),
('98', 'ESPINOSA DE LOS MONTEROS', 'DE SIM�N', 'IV�N', 'FAVOR', 1),
('99', 'ESTEBAN', 'BRAVO', 'AITOR', 'FAVOR', 1),
('100', 'ESTEBAN', 'CALONJE', 'CRISTINA ALICIA', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('101', 'FAG�NDEZ', 'CAMPO', 'ANTIDIO', 'FAVOR', 1),
('102', 'FANECA', 'L�PEZ', 'MAR�A LUISA', 'FAVOR', 2),
('103', 'FERN�NDEZ', 'BEN�ITEZ', 'ANDREA', 'FAVOR', 1),
('104', 'FERN�NDEZ', 'CASERO', 'ANA BEL�N', 'FAVOR', 1),
('105', 'FERN�NDEZ', 'CASTA��N', 'SOF�A', 'FAVOR', 1),
('106', 'FERN�NDEZ', 'HERN�NDEZ', 'PEDRO', 'FAVOR', 1),
('107', 'FERN�NDEZ', 'R�OS', 'TOM�S', 'FAVOR', 1),
('108', 'FERN�NDEZ-LOMANA', 'GUTI�RREZ', 'RAFAEL', 'FAVOR', 1),
('109', 'FERN�NDEZ-ROCA', 'SU�REZ', 'CARLOS HUGO', 'FAVOR', 1),
('110', 'FERRER', 'TESORO', 'SONIA', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('111', 'FIGAREDO', '�LVAREZ-SALA', 'JOS� MAR�A', 'FAVOR', 1),
('112', 'FRANCO', 'CARMONA', 'ISABEL', 'FAVOR', 2),
('113', 'FUENTES', 'CURBELO', 'JUAN BERNARDO', 'FAVOR', 1),
('114', 'GAGO', 'BUGAR�N', 'DIEGO', 'FAVOR', 1),
('115', 'GAMARRA', 'RUIZ-CLAVIJO', 'CONCEPCI�N', 'FAVOR', 1),
('116', 'GAMAZO', 'MIC�', '�SCAR', 'FAVOR', 1),
('117', 'GARC�S', 'SAN AGUST�N', 'MARIO', 'FAVOR', 1),
('118', 'GARC�A', 'ADANERO', 'CARLOS', 'FAVOR', 1),
('119', 'GARC�A', 'CHAVARR�A', 'MAR�A MONTSERRAT', 'FAVOR', 1),
('120', 'GARC�A', 'D�EZ', 'JOAQU�N MAR�A', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('121', 'GARC�A', 'EGEA', 'TEODORO', 'FAVOR', 1),
('122', 'GARC�A', 'G�MEZ', 'VALENT�N', 'FAVOR', 2),
('123', 'GARC�A', 'L�PEZ', 'MARIBEL', 'FAVOR', 1),
('124', 'GARC�A', 'MOR�S', 'ROBERTO', 'FAVOR', 1),
('125', 'GARC�A', 'PUIG', 'MAR�A DEL MAR', 'FAVOR', 1),
('126', 'GARC�A', 'RODR�GUEZ', 'ALICIA', 'FAVOR', 1),
('127', 'GARC�A', 'TEJERINA', 'ISABEL', 'FAVOR', 1),
('128', 'GARC�A-PELAYO', 'JURADO', 'MAR�A JOS�', 'FAVOR', 1),
('129', 'GARRIDO', 'GUTI�RREZ', 'PILAR', 'FAVOR', 1),
('130', 'GARRIGA', 'VAZ DE CONCICAO', 'IGNACIO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('131', 'GARZ�N', 'ESPINOSA', 'ALBERTO', 'FAVOR', 1),
('132', 'G�ZQUEZ', 'COLLADO', 'PALOMA', 'FAVOR', 2),
('133', 'GESTOSO', 'DE MIGUEL', 'LUIS', 'FAVOR', 1),
('134', 'GIL', 'L�ZARO', 'IGNACIO', 'FAVOR', 1),
('135', 'GIM�NEZ', 'GIM�NEZ', 'SARA', 'FAVOR', 1),
('136', 'G�MEZ', 'HERN�NDEZ', 'HECTOR', 'FAVOR', 1),
('137', 'G�MEZ-REINO', 'VARELA', 'ANTONIO', 'FAVOR', 1),
('138', 'GONZ�LEZ', 'CABALLERO', 'MIGUEL �NGEL', 'FAVOR', 1),
('139', 'GONZ�LEZ', 'COELLO DE PORTUGAL', 'VICTOR', 'FAVOR', 1),
('140', 'GONZ�LEZ', 'GUINDA', 'MAR�A DEL CARMEN', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('141', 'GONZ�LEZ', 'P�REZ', 'ARIGONA', 'FAVOR', 1),
('142', 'GONZ�LEZ', 'RAMOS', 'MANUEL GABRIEL', 'FAVOR', 2),
('143', 'GONZ�LEZ', 'TEROL', 'ANTONIO', 'FAVOR', 1),
('144', 'GONZ�LEZ', 'V�ZQUEZ', 'MARTA', 'FAVOR', 1),
('145', 'GOROSPE', 'ELEZCANO', 'JOSUNE', 'FAVOR', 1),
('146', 'GRANOLLERS', 'CUNILLERA', 'IN�S', 'FAVOR', 1),
('147', 'GUAITA', 'ESTERUELAS', 'SANDRA', 'FAVOR', 1),
('148', 'GUERRA', 'L�PEZ', 'SONIA', 'FAVOR', 1),
('149', 'GUIJARRO', 'CEBALLOS', 'MAR�A', 'FAVOR', 1),
('150', 'GUIJARRO', 'GARC�A', 'TXEMA', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('151', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('152', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('153', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('154', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('155', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('156', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('157', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('158', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('159', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('160', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('161', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('162', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('163', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('164', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('165', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('166', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('167', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('168', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('169', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('170', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('171', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('172', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('173', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('174', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('175', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('176', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('177', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('178', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('179', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('180', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('181', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('182', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('183', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('184', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('185', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('186', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('187', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('188', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('189', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('190', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('191', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('192', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('193', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('194', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('195', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('196', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('197', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('198', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('199', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('200', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('201', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('202', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('203', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('204', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('205', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('206', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('207', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('208', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('209', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('210', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('211', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('212', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('213', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('214', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('215', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('216', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('217', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('218', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('219', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('220', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('221', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('222', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('223', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('224', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('225', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('226', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('227', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('228', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('229', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('230', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('231', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('232', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('233', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('234', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('235', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('236', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('237', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('238', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('239', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('240', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('241', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('242', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('243', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('244', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('245', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('246', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('247', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('248', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('249', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('250', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('251', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('252', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('253', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('254', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('255', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('256', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('257', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('258', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('259', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('260', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('261', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('262', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('263', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('264', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('265', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('266', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('267', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('268', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('269', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('270', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('271', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('272', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('273', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('274', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('275', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('276', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('277', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('278', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('279', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('280', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('281', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('282', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('283', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('284', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('285', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('286', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('287', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('288', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('289', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('290', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('291', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('292', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('293', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('294', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('295', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('296', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('297', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('298', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('299', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('300', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('301', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('302', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('303', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('304', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('305', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('306', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('307', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('308', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('309', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('310', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('311', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('312', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('313', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('314', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('315', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('316', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('317', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('318', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('319', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('320', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('321', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('322', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('323', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('324', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('325', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('326', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('327', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('328', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('329', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('330', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('331', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('332', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('333', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('334', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('335', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('336', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('337', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('338', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('339', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('340', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)

INSERT INTO DIPUTADO (ID, APELLIDO1, APELLIDO2, NOMBRE, VOTO, PARTIDO_ID) VALUES 
('341', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('342', 'SANCHEZ', 'CASTEJ�N', 'PEDRO', 'FAVOR', 2),
('343', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('344', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('345', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('346', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('347', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('348', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('349', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1),
('350', 'CASADO', 'BLANCO', 'PABLO', 'FAVOR', 1)








INSERT INTO LEY (ID, DESCRIPCION, FECHA, NOMBRE, RESULTADO) VALUES ('1', 'ES UNA LEY MUY IMPORTANTE','1996-06-16', 'LEY DEL ABORTO', 'FAVOR'),('2', 'ES UNA LEY MENOS IMPORTANTE','1993-09-21', 'LEY DEL ABORTO2', 'FAVOR')



